(function(){
  "use strict";
  window.SkillMatchSwipe={init:function(){
    var SM=window.SkillMatch, mount=SM.$("#swipeMount"); if(!mount) return;
    mount.innerHTML='<div class="grid grid--2"><div class="app-card panel"><div class="swipe-stage" id="swipeStage"></div><div class="swipe-actions"><button class="swipe-btn swipe-btn--nope" id="swipeNope">Pass</button><button class="swipe-btn swipe-btn--like" id="swipeLike">Like</button></div><div class="chips"><span class="chip">Matchs <b id="tallyLike">'+SM.state.likes+'</b></span><span class="chip">Passes <b id="tallyNope">'+SM.state.passes+'</b></span><span class="chip">Vues <b id="tallySeen">'+SM.state.seen+'</b></span></div></div><div class="app-card panel"><h2>Match</h2><p class="muted">Lorsqu\'un match est effectue : animation, popup, notification, conversation et mission sont crees automatiquement.</p><div id="matchFeed" class="list"></div></div></div>';
    var stage=SM.$("#swipeStage"), stack=SM.state.candidates.slice(), active=null, threshold=95;
    function card(c,i){return '<article class="swipe-card" style="z-index:'+(10-i)+';transform:translateY('+(i*12)+'px) scale('+(1-i*.045)+')"><img src="'+c.photo+'" alt=""><div class="swipe-stamp like">MATCH</div><div class="swipe-stamp nope">NON</div><div class="swipe-info"><div><h3>'+c.name+' <span>'+c.age+' ans</span></h3><p>'+c.distance+' · '+c.rating+' etoiles · '+c.missions+' missions</p></div><strong>'+c.price+'</strong></div><div class="chips">'+c.badges.concat(c.skills).map(function(s){return '<span class="chip">'+s+'</span>';}).join("")+'</div><p class="muted">'+c.time+' estime · '+c.availability+'</p></article>';}
    function render(){stage.innerHTML=stack.slice(0,3).map(card).join(""); active=stage.firstElementChild; bind(active);}
    function bind(el){if(!el)return;var sx=0,sy=0,dx=0,drag=false;el.onpointerdown=function(e){drag=true;sx=e.clientX;sy=e.clientY;el.style.transition="none";el.setPointerCapture(e.pointerId);};el.onpointermove=function(e){if(!drag)return;dx=e.clientX-sx;var dy=e.clientY-sy;el.style.transform="translate("+dx+"px,"+dy+"px) rotate("+(dx*.055)+"deg)";el.dataset.verdict=dx>threshold?"like":dx<-threshold?"nope":"";};el.onpointerup=function(){if(!drag)return;drag=false;if(dx>threshold) fly(1);else if(dx<-threshold) fly(-1);else{el.style.transition="";el.style.transform="";el.dataset.verdict="";}};}
    function fly(dir){if(!active)return;var c=stack[0];active.style.transition="transform .42s var(--ease),opacity .32s";active.style.transform="translate("+(dir*(innerWidth+220))+"px,40px) rotate("+(dir*24)+"deg)";active.style.opacity=0;SM.state.seen++; if(dir>0){SM.state.likes++;match(c);}else{SM.state.passes++;SM.toast("Profil passe","La pile continue avec de nouveaux profils.");}stack.shift();update();setTimeout(function(){if(!stack.length)stack=SM.state.candidates.slice();render();},300);}
    function match(c){SM.toast("Match avec "+c.name,"Conversation et mission creees automatiquement.");SM.addNotification("Match avec "+c.name,c.availability+" · "+c.price,"match");SM.state.conversations.unshift({id:c.name,name:c.name,avatar:c.photo,last:"On peut finaliser le contrat.",messages:[["them","Salut, je suis disponible pour cette mission."],["me","Parfait, je t'envoie le contrat SkillMatch."]]});SM.state.missions.unshift({id:Date.now(),title:c.skills[0]+" - mission matchee",cat:"match",person:c.name,status:"Contrat pret",price:parseInt(c.price,10)||40,distance:parseFloat(c.distance)||1,rating:c.rating,date:c.availability,img:c.photo});SM.$("#matchFeed").insertAdjacentHTML("afterbegin",'<div class="row"><img src="'+c.photo+'" alt=""><div class="row__main"><strong>'+c.name+'</strong><p>Conversation, contrat et paiement simules.</p></div><span class="row__meta">MATCH</span></div>');}
    function update(){SM.$("#tallyLike").textContent=SM.state.likes;SM.$("#tallyNope").textContent=SM.state.passes;SM.$("#tallySeen").textContent=SM.state.seen;}
    SM.$("#swipeLike").onclick=function(){fly(1);};SM.$("#swipeNope").onclick=function(){fly(-1);};document.onkeydown=function(e){if(SM.state.route!=="decouverte")return;if(e.key==="ArrowRight")fly(1);if(e.key==="ArrowLeft")fly(-1);};render();
  }};
})();
