(function(){
  "use strict";
  window.SkillMatchTracker={init:function(){
    var SM=window.SkillMatch, mount=SM.$("#trackerMount"); if(!mount) return;
    mount.innerHTML='<div class="tracker"><div class="row"><img src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80" alt=""><div class="row__main"><strong>Karim B.</strong><p>Montage de meubles · 0,5 km</p></div><span class="row__meta" id="trackerEta">ETA</span></div><div class="tracker-progress"><i id="trackerBar"></i></div><svg class="map" viewBox="0 0 680 260" role="img" aria-label="Carte simulee"><path d="M45 210 C145 95 265 120 355 55 C455 -15 570 70 635 150" fill="none" stroke="rgba(243,238,225,.22)" stroke-width="8" stroke-linecap="round"/><path d="M45 210 C145 95 265 120 355 55 C455 -15 570 70 635 150" fill="none" stroke="#B6FF3C" stroke-width="3" stroke-dasharray="10 12"/><circle cx="45" cy="210" r="10" fill="#C1622D"/><circle cx="635" cy="150" r="12" fill="#B6FF3C"/><circle class="map-runner" r="9" fill="#F3EEE1"/></svg><div class="list" id="trackerSteps"></div><div class="tracker-controls"><button class="btn btn--accent" id="trackerPlay">Lancer la simulation</button><button class="btn btn--ghost" id="trackerReset">Rejouer</button></div></div>';
    var steps=["Mission acceptee","Prestataire en route","Arrive sur place","Mission en cours","Terminee & payee"], cur=-1,timer=null,playing=false;
    function draw(){SM.$("#trackerSteps").innerHTML=steps.map(function(s,i){return '<div class="row '+(i<cur?"done":"")+' '+(i===cur?"active":"")+'"><span class="chip">'+(i<cur?"✓":i+1)+'</span><div class="row__main"><strong>'+s+'</strong><p>'+(i<=cur?new Date().toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"}):"En attente")+'</p></div></div>';}).join("");SM.$("#trackerBar").style.width=(Math.max(cur,0)/(steps.length-1)*100)+"%";SM.$("#trackerEta").textContent=cur<1?"ETA":cur===1?"8 min":cur===2?"2 min":cur===3?"En cours":"Fait";}
    function next(){cur++;draw();if(cur>=steps.length-1){playing=false;SM.$("#trackerPlay").textContent="Lancer la simulation";SM.toast("Mission terminee & payee","40 EUR verses sur le portefeuille.");SM.state.balance+=40;return;}timer=setTimeout(next,1900);}
    SM.$("#trackerPlay").onclick=function(){if(playing){clearTimeout(timer);playing=false;this.textContent="Reprendre";return;}playing=true;this.textContent="Mettre en pause";if(cur>=steps.length-1)cur=-1;next();};
    SM.$("#trackerReset").onclick=function(){clearTimeout(timer);playing=false;cur=-1;SM.$("#trackerPlay").textContent="Lancer la simulation";draw();};
    draw();
  }};
})();
